version: '3'
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - /home/${USER}/mongodb/data:/data/db
    ports:
      - '27017:27017'