version: '3'
services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - /home/${USER}/mongodb/data:/data/db
    ports:
      - '27017:27017'
  redis:
    image: redis:alpine3.13
    container_name: docker_redis
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 4G
        reservations:
          cpus: "0.25"
          memory: 1G
    volumes:
      - /home/${USER}/redis/data:/data
    ports:
      - 6379:6379